spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.56.10:3306/gulimall_pms
    url: jdbc:mysql://localhost:3306/gulimall_pms?serverTimezone=Asia/Shanghai
    username: root
#    password: root
    password: 123456
    hikari:
      max-lifetime: 30000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tFYUsVZNxWg5CzF9nFY
      secret-key: xMSlavcBD0wIjSxNPRj8xAhcXIVUPd
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
  thymeleaf:
    cache: false  # close cache, Can be real-time access to the latest data
  redis:
    host: 192.168.56.10 #TODO replace linux server IP
    port: 6379

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 #deleted
      logic-not-delete-value: 0 #not delete
server:
  port: 10000
logging:
  level:
    com.atguigu.gulimall: debug

#自定义线程池
gulimall:
  thread:
    core-thread: 20
    max-thread: 200
    max-alive-time: 10


